[2023-06-09 13:40:12,812] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-2 manual__2023-06-09T13:40:06.352040+00:00 [queued]>
[2023-06-09 13:40:12,826] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-2 manual__2023-06-09T13:40:06.352040+00:00 [queued]>
[2023-06-09 13:40:12,826] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 13:40:12,826] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2023-06-09 13:40:12,826] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 13:40:12,844] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt-2> on 2023-06-09 13:40:06.352040+00:00
[2023-06-09 13:40:12,850] {standard_task_runner.py:52} INFO - Started process 5557 to run task
[2023-06-09 13:40:12,852] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'dbt-2', 'manual__2023-06-09T13:40:06.352040+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6kr5tq4i', '--error-file', '/tmp/tmp3fzdicjn']
[2023-06-09 13:40:12,852] {standard_task_runner.py:77} INFO - Job 28: Subtask dbt-2
[2023-06-09 13:40:12,912] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.dbt-2 manual__2023-06-09T13:40:06.352040+00:00 [running]> on host d78e0722255b
[2023-06-09 13:40:12,975] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=dbt-2
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T13:40:06.352040+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T13:40:06.352040+00:00
[2023-06-09 13:40:12,976] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-09 13:40:12,977] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --models dbt-2 --profiles-dir /opt/***/dbt/part3/ --project-dir /opt/***/dbt/part3/']
[2023-06-09 13:40:12,992] {subprocess.py:85} INFO - Output:
[2023-06-09 13:40:15,316] {subprocess.py:89} INFO - [0m13:40:15  Running with dbt=1.5.1
[2023-06-09 13:40:15,440] {subprocess.py:89} INFO - [0m13:40:15  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-09 13:40:15,440] {subprocess.py:89} INFO - There are 1 unused configuration paths:
[2023-06-09 13:40:15,440] {subprocess.py:89} INFO - - models.part3.example
[2023-06-09 13:40:15,453] {subprocess.py:89} INFO - [0m13:40:15  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 307 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-09 13:40:15,454] {subprocess.py:89} INFO - [0m13:40:15  The selection criterion 'dbt-2' does not match any nodes
[2023-06-09 13:40:15,455] {subprocess.py:89} INFO - [0m13:40:15
[2023-06-09 13:40:15,456] {subprocess.py:89} INFO - [0m13:40:15  Nothing to do. Try checking your model configs and model specification args
[2023-06-09 13:40:16,440] {subprocess.py:93} INFO - Command exited with return code 0
[2023-06-09 13:40:16,460] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=dbt-2, execution_date=20230609T134006, start_date=20230609T134012, end_date=20230609T134016
[2023-06-09 13:40:16,514] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 13:40:16,578] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
