[2023-06-09 08:04:24,176] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-1 manual__2023-06-09T08:04:23.661284+00:00 [queued]>
[2023-06-09 08:04:24,183] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-1 manual__2023-06-09T08:04:23.661284+00:00 [queued]>
[2023-06-09 08:04:24,183] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 08:04:24,183] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2023-06-09 08:04:24,183] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 08:04:24,193] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt-1> on 2023-06-09 08:04:23.661284+00:00
[2023-06-09 08:04:24,196] {standard_task_runner.py:52} INFO - Started process 1281 to run task
[2023-06-09 08:04:24,198] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'dbt-1', 'manual__2023-06-09T08:04:23.661284+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmhn1zldb', '--error-file', '/tmp/tmpqj88xlol']
[2023-06-09 08:04:24,198] {standard_task_runner.py:77} INFO - Job 13: Subtask dbt-1
[2023-06-09 08:04:24,232] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.dbt-1 manual__2023-06-09T08:04:23.661284+00:00 [running]> on host 00a2553a67b9
[2023-06-09 08:04:24,268] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=dbt-1
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T08:04:23.661284+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T08:04:23.661284+00:00
[2023-06-09 08:04:24,268] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-09 08:04:24,269] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --models dbt-1 --projects_dir /opt/dbt/profiles.yml']
[2023-06-09 08:04:24,275] {subprocess.py:85} INFO - Output:
[2023-06-09 08:04:26,890] {subprocess.py:89} INFO - Usage: dbt run [OPTIONS]
[2023-06-09 08:04:26,890] {subprocess.py:89} INFO - Try 'dbt run -h' for help.
[2023-06-09 08:04:26,890] {subprocess.py:89} INFO - 
[2023-06-09 08:04:26,891] {subprocess.py:89} INFO - Error: No such option: --projects_dir (Possible options: --profiles-dir, --project-dir)
[2023-06-09 08:04:26,970] {subprocess.py:93} INFO - Command exited with return code 2
[2023-06-09 08:04:26,979] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-09 08:04:26,984] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=my_dag, task_id=dbt-1, execution_date=20230609T080423, start_date=20230609T080424, end_date=20230609T080426
[2023-06-09 08:04:26,995] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task dbt-1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-09 08:04:27,019] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 08:04:27,044] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
