[2023-06-09 08:08:14,752] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-1 manual__2023-06-09T08:08:13.617134+00:00 [queued]>
[2023-06-09 08:08:14,759] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-1 manual__2023-06-09T08:08:13.617134+00:00 [queued]>
[2023-06-09 08:08:14,759] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 08:08:14,759] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2023-06-09 08:08:14,759] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 08:08:14,770] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt-1> on 2023-06-09 08:08:13.617134+00:00
[2023-06-09 08:08:14,773] {standard_task_runner.py:52} INFO - Started process 1458 to run task
[2023-06-09 08:08:14,775] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'dbt-1', 'manual__2023-06-09T08:08:13.617134+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp34es3uf9', '--error-file', '/tmp/tmpoart1vbn']
[2023-06-09 08:08:14,775] {standard_task_runner.py:77} INFO - Job 15: Subtask dbt-1
[2023-06-09 08:08:14,814] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.dbt-1 manual__2023-06-09T08:08:13.617134+00:00 [running]> on host 00a2553a67b9
[2023-06-09 08:08:14,852] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=dbt-1
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T08:08:13.617134+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T08:08:13.617134+00:00
[2023-06-09 08:08:14,852] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-09 08:08:14,853] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --models dbt-1 --profiles-dir /opt/dbt/profiles.yml']
[2023-06-09 08:08:14,861] {subprocess.py:85} INFO - Output:
[2023-06-09 08:08:16,975] {subprocess.py:89} INFO - Usage: dbt run [OPTIONS]
[2023-06-09 08:08:16,975] {subprocess.py:89} INFO - Try 'dbt run -h' for help.
[2023-06-09 08:08:16,975] {subprocess.py:89} INFO - 
[2023-06-09 08:08:16,975] {subprocess.py:89} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/dbt/profiles.yml' does not exist.
[2023-06-09 08:08:17,049] {subprocess.py:93} INFO - Command exited with return code 2
[2023-06-09 08:08:17,058] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-09 08:08:17,062] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=my_dag, task_id=dbt-1, execution_date=20230609T080813, start_date=20230609T080814, end_date=20230609T080817
[2023-06-09 08:08:17,073] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task dbt-1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-09 08:08:17,114] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 08:08:17,141] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
